// AUTO-GENERATED by build_spec_table.py — do not edit manually
// Source: AI Hub 71861 Training labels (TL.zip) median statistics
using System.Collections.Generic;
using UnityEngine;

namespace ARLogistics.Data
{
    /// <summary>
    /// 카테고리(classId) × size_id 별 실측 치수/무게 중앙값 조회 테이블.
    /// AI Hub 물류공간 예측 데이터셋 97,910개 어노테이션에서 자동 집계.
    /// </summary>
    public static class ProductSpecTable
    {
        public static readonly Dictionary<int, string> SizeNames = new()
        {
            { 1, "극소형" },
            { 2, "소형" },
            { 3, "중형" },
            { 4, "대형" },
            { 5, "특대형" },
            { 6, "특수" },
        };

        public static readonly string[] ClassNames = new[]
        {
            "01_가공식품",
            "02_신선식품",
            "03_일상용품",
            "05_의약품/의료기기",
            "06_교육/문화용품",
            "07_디지털/가전",
            "08_가구/인테리어",
            "09_의류",
            "10_전문스포츠/레저",
            "11_패션잡화",
        };

        [System.Serializable]
        public struct Spec
        {
            public float LengthCm;    // 길이 (cm)
            public float WidthCm;     // 너비 (cm)
            public float HeightCm;    // 높이 (cm)
            public float WeightKg;    // 무게 (kg)
            public float FragilePct;  // 파손주의 비율 (%)
            public float IrregularPct;// 비정형 비율 (%)
            public int   SampleCount; // 집계 샘플 수

            // Unity 단위(m) 변환 편의 프로퍼티
            public float LengthM    => LengthCm   * 0.01f;
            public float WidthM     => WidthCm    * 0.01f;
            public float HeightM    => HeightCm   * 0.01f;
            public bool  IsFragile  => FragilePct  > 50f;
            public bool  IsIrregular=> IrregularPct > 50f;
        }

        // Key = classId * 10 + size_id
        private static readonly Dictionary<int, Spec> _table = new()
        {
            // [0]01_가공식품  size_id=1(극소형)  n=17,487
            { 1, new Spec { LengthCm=17.0f, WidthCm=16.0f, HeightCm=12.0f, WeightKg=0.526f, FragilePct=63.8f, IrregularPct=56.8f, SampleCount=17487 } },
            // [0]01_가공식품  size_id=2(소형)  n=7,956
            { 2, new Spec { LengthCm=32.0f, WidthCm=25.0f, HeightCm=19.6f, WeightKg=2.246f, FragilePct=35.6f, IrregularPct=31.3f, SampleCount=7956 } },
            // [0]01_가공식품  size_id=3(중형)  n=2,273
            { 3, new Spec { LengthCm=40.0f, WidthCm=31.0f, HeightCm=25.0f, WeightKg=5.044f, FragilePct=24.3f, IrregularPct=19.0f, SampleCount=2273 } },
            // [0]01_가공식품  size_id=4(대형)  n=750
            { 4, new Spec { LengthCm=35.0f, WidthCm=28.6f, HeightCm=25.0f, WeightKg=10.969f, FragilePct=52.0f, IrregularPct=24.0f, SampleCount=750 } },
            // [0]01_가공식품  size_id=5(특대형)  n=450
            { 5, new Spec { LengthCm=30.0f, WidthCm=26.0f, HeightCm=29.2f, WeightKg=15.57f, FragilePct=52.0f, IrregularPct=32.0f, SampleCount=450 } },
            // [0]01_가공식품  size_id=6(특수)  n=96
            { 6, new Spec { LengthCm=63.5f, WidthCm=42.2f, HeightCm=15.1f, WeightKg=20.373f, FragilePct=87.5f, IrregularPct=81.2f, SampleCount=96 } },
            // [1]02_신선식품  size_id=1(극소형)  n=538
            { 11, new Spec { LengthCm=22.4f, WidthCm=20.7f, HeightCm=8.3f, WeightKg=0.714f, FragilePct=66.9f, IrregularPct=66.9f, SampleCount=538 } },
            // [1]02_신선식품  size_id=2(소형)  n=462
            { 12, new Spec { LengthCm=35.0f, WidthCm=26.0f, HeightCm=14.0f, WeightKg=2.314f, FragilePct=42.9f, IrregularPct=41.6f, SampleCount=462 } },
            // [1]02_신선식품  size_id=3(중형)  n=54
            { 13, new Spec { LengthCm=45.0f, WidthCm=33.8f, HeightCm=17.1f, WeightKg=8.038f, FragilePct=66.7f, IrregularPct=44.4f, SampleCount=54 } },
            // [1]02_신선식품  size_id=4(대형)  n=102
            { 14, new Spec { LengthCm=56.2f, WidthCm=37.5f, HeightCm=11.3f, WeightKg=10.124f, FragilePct=70.6f, IrregularPct=70.6f, SampleCount=102 } },
            // [1]02_신선식품  size_id=5(특대형)  n=6
            { 15, new Spec { LengthCm=48.7f, WidthCm=25.2f, HeightCm=30.6f, WeightKg=19.006f, FragilePct=100.0f, IrregularPct=0.0f, SampleCount=6 } },
            // [1]02_신선식품  size_id=6(특수)  n=24
            { 16, new Spec { LengthCm=70.0f, WidthCm=50.0f, HeightCm=30.0f, WeightKg=21.945f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=24 } },
            // [2]03_일상용품  size_id=1(극소형)  n=30,882
            { 21, new Spec { LengthCm=20.0f, WidthCm=20.0f, HeightCm=9.1f, WeightKg=0.288f, FragilePct=16.5f, IrregularPct=42.4f, SampleCount=30882 } },
            // [2]03_일상용품  size_id=2(소형)  n=10,578
            { 22, new Spec { LengthCm=35.5f, WidthCm=26.0f, HeightCm=20.0f, WeightKg=1.848f, FragilePct=6.2f, IrregularPct=17.0f, SampleCount=10578 } },
            // [2]03_일상용품  size_id=3(중형)  n=4,523
            { 23, new Spec { LengthCm=46.0f, WidthCm=32.0f, HeightCm=25.0f, WeightKg=2.208f, FragilePct=2.7f, IrregularPct=18.2f, SampleCount=4523 } },
            // [2]03_일상용품  size_id=4(대형)  n=1,174
            { 24, new Spec { LengthCm=55.0f, WidthCm=40.0f, HeightCm=29.0f, WeightKg=2.157f, FragilePct=2.6f, IrregularPct=26.9f, SampleCount=1174 } },
            // [2]03_일상용품  size_id=5(특대형)  n=1,114
            { 25, new Spec { LengthCm=60.0f, WidthCm=50.0f, HeightCm=30.0f, WeightKg=4.201f, FragilePct=1.1f, IrregularPct=6.5f, SampleCount=1114 } },
            // [2]03_일상용품  size_id=6(특수)  n=204
            { 26, new Spec { LengthCm=70.0f, WidthCm=50.0f, HeightCm=50.0f, WeightKg=8.063f, FragilePct=20.6f, IrregularPct=23.5f, SampleCount=204 } },
            // [3]05_의약품/의료기기  size_id=1(극소형)  n=804
            { 31, new Spec { LengthCm=15.6f, WidthCm=23.4f, HeightCm=7.2f, WeightKg=0.306f, FragilePct=67.2f, IrregularPct=29.9f, SampleCount=804 } },
            // [3]05_의약품/의료기기  size_id=2(소형)  n=36
            { 32, new Spec { LengthCm=35.5f, WidthCm=26.0f, HeightCm=21.0f, WeightKg=0.929f, FragilePct=16.7f, IrregularPct=16.7f, SampleCount=36 } },
            // [3]05_의약품/의료기기  size_id=3(중형)  n=36
            { 33, new Spec { LengthCm=40.5f, WidthCm=33.0f, HeightCm=29.0f, WeightKg=2.196f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=36 } },
            // [3]05_의약품/의료기기  size_id=4(대형)  n=6
            { 34, new Spec { LengthCm=55.0f, WidthCm=40.0f, HeightCm=40.0f, WeightKg=9.689f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=6 } },
            // [3]05_의약품/의료기기  size_id=5(특대형)  n=18
            { 35, new Spec { LengthCm=70.0f, WidthCm=50.0f, HeightCm=30.0f, WeightKg=3.155f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=18 } },
            // [4]06_교육/문화용품  size_id=1(극소형)  n=3,544
            { 41, new Spec { LengthCm=12.9f, WidthCm=20.0f, HeightCm=3.4f, WeightKg=0.152f, FragilePct=39.5f, IrregularPct=66.8f, SampleCount=3544 } },
            // [4]06_교육/문화용품  size_id=2(소형)  n=120
            { 42, new Spec { LengthCm=35.1f, WidthCm=23.1f, HeightCm=23.4f, WeightKg=0.937f, FragilePct=60.0f, IrregularPct=45.0f, SampleCount=120 } },
            // [4]06_교육/문화용품  size_id=3(중형)  n=95
            { 43, new Spec { LengthCm=50.0f, WidthCm=29.3f, HeightCm=25.0f, WeightKg=0.856f, FragilePct=56.8f, IrregularPct=0.0f, SampleCount=95 } },
            // [4]06_교육/문화용품  size_id=4(대형)  n=30
            { 44, new Spec { LengthCm=59.8f, WidthCm=40.0f, HeightCm=37.5f, WeightKg=2.387f, FragilePct=40.0f, IrregularPct=0.0f, SampleCount=30 } },
            // [4]06_교육/문화용품  size_id=5(특대형)  n=30
            { 45, new Spec { LengthCm=55.0f, WidthCm=40.0f, HeightCm=40.0f, WeightKg=16.689f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=30 } },
            // [4]06_교육/문화용품  size_id=6(특수)  n=54
            { 46, new Spec { LengthCm=70.0f, WidthCm=50.0f, HeightCm=50.0f, WeightKg=10.563f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=54 } },
            // [5]07_디지털/가전  size_id=1(극소형)  n=2,945
            { 51, new Spec { LengthCm=12.3f, WidthCm=19.4f, HeightCm=4.7f, WeightKg=0.184f, FragilePct=74.5f, IrregularPct=28.9f, SampleCount=2945 } },
            // [5]07_디지털/가전  size_id=2(소형)  n=516
            { 52, new Spec { LengthCm=35.0f, WidthCm=26.0f, HeightCm=22.0f, WeightKg=1.787f, FragilePct=23.3f, IrregularPct=1.2f, SampleCount=516 } },
            // [5]07_디지털/가전  size_id=3(중형)  n=402
            { 53, new Spec { LengthCm=48.0f, WidthCm=32.0f, HeightCm=30.0f, WeightKg=4.825f, FragilePct=17.9f, IrregularPct=1.5f, SampleCount=402 } },
            // [5]07_디지털/가전  size_id=4(대형)  n=228
            { 54, new Spec { LengthCm=52.0f, WidthCm=39.0f, HeightCm=34.0f, WeightKg=7.873f, FragilePct=10.5f, IrregularPct=0.0f, SampleCount=228 } },
            // [5]07_디지털/가전  size_id=5(특대형)  n=149
            { 55, new Spec { LengthCm=60.0f, WidthCm=50.0f, HeightCm=30.0f, WeightKg=9.201f, FragilePct=4.0f, IrregularPct=0.0f, SampleCount=149 } },
            // [5]07_디지털/가전  size_id=6(특수)  n=126
            { 56, new Spec { LengthCm=70.0f, WidthCm=50.0f, HeightCm=50.0f, WeightKg=16.563f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=126 } },
            // [6]08_가구/인테리어  size_id=1(극소형)  n=2,777
            { 61, new Spec { LengthCm=14.9f, WidthCm=20.5f, HeightCm=6.6f, WeightKg=0.264f, FragilePct=41.7f, IrregularPct=61.4f, SampleCount=2777 } },
            // [6]08_가구/인테리어  size_id=2(소형)  n=576
            { 62, new Spec { LengthCm=38.0f, WidthCm=30.0f, HeightCm=14.5f, WeightKg=1.05f, FragilePct=11.5f, IrregularPct=5.2f, SampleCount=576 } },
            // [6]08_가구/인테리어  size_id=3(중형)  n=714
            { 63, new Spec { LengthCm=48.0f, WidthCm=35.0f, HeightCm=31.5f, WeightKg=3.008f, FragilePct=7.6f, IrregularPct=3.4f, SampleCount=714 } },
            // [6]08_가구/인테리어  size_id=4(대형)  n=750
            { 64, new Spec { LengthCm=54.0f, WidthCm=40.0f, HeightCm=40.0f, WeightKg=3.79f, FragilePct=4.8f, IrregularPct=1.6f, SampleCount=750 } },
            // [6]08_가구/인테리어  size_id=5(특대형)  n=661
            { 65, new Spec { LengthCm=52.0f, WidthCm=48.0f, HeightCm=40.0f, WeightKg=3.744f, FragilePct=4.2f, IrregularPct=3.3f, SampleCount=661 } },
            // [6]08_가구/인테리어  size_id=6(특수)  n=214
            { 66, new Spec { LengthCm=70.0f, WidthCm=50.0f, HeightCm=50.0f, WeightKg=10.563f, FragilePct=7.9f, IrregularPct=7.9f, SampleCount=214 } },
            // [7]09_의류  size_id=1(극소형)  n=978
            { 71, new Spec { LengthCm=32.0f, WidthCm=37.6f, HeightCm=3.3f, WeightKg=0.298f, FragilePct=0.0f, IrregularPct=94.8f, SampleCount=978 } },
            // [7]09_의류  size_id=2(소형)  n=113
            { 72, new Spec { LengthCm=34.8f, WidthCm=41.0f, HeightCm=5.7f, WeightKg=0.638f, FragilePct=0.0f, IrregularPct=100.0f, SampleCount=113 } },
            // [7]09_의류  size_id=4(대형)  n=18
            { 74, new Spec { LengthCm=68.8f, WidthCm=49.3f, HeightCm=8.5f, WeightKg=1.496f, FragilePct=0.0f, IrregularPct=100.0f, SampleCount=18 } },
            // [7]09_의류  size_id=5(특대형)  n=78
            { 75, new Spec { LengthCm=70.0f, WidthCm=50.0f, HeightCm=30.0f, WeightKg=6.055f, FragilePct=0.0f, IrregularPct=7.7f, SampleCount=78 } },
            // [8]10_전문스포츠/레저  size_id=1(극소형)  n=1,230
            { 81, new Spec { LengthCm=11.5f, WidthCm=21.5f, HeightCm=4.1f, WeightKg=0.126f, FragilePct=15.1f, IrregularPct=66.3f, SampleCount=1230 } },
            // [8]10_전문스포츠/레저  size_id=2(소형)  n=156
            { 82, new Spec { LengthCm=34.9f, WidthCm=24.8f, HeightCm=12.8f, WeightKg=1.899f, FragilePct=0.0f, IrregularPct=53.8f, SampleCount=156 } },
            // [8]10_전문스포츠/레저  size_id=3(중형)  n=138
            { 83, new Spec { LengthCm=30.0f, WidthCm=25.4f, HeightCm=14.0f, WeightKg=5.548f, FragilePct=0.0f, IrregularPct=21.7f, SampleCount=138 } },
            // [8]10_전문스포츠/레저  size_id=4(대형)  n=125
            { 84, new Spec { LengthCm=31.0f, WidthCm=21.0f, HeightCm=19.0f, WeightKg=10.316f, FragilePct=0.0f, IrregularPct=4.8f, SampleCount=125 } },
            // [8]10_전문스포츠/레저  size_id=5(특대형)  n=120
            { 85, new Spec { LengthCm=35.0f, WidthCm=26.0f, HeightCm=19.2f, WeightKg=15.921f, FragilePct=0.0f, IrregularPct=5.0f, SampleCount=120 } },
            // [8]10_전문스포츠/레저  size_id=6(특수)  n=156
            { 86, new Spec { LengthCm=40.0f, WidthCm=31.5f, HeightCm=21.5f, WeightKg=25.59f, FragilePct=0.0f, IrregularPct=0.0f, SampleCount=156 } },
            // [9]11_패션잡화  size_id=1(극소형)  n=902
            { 91, new Spec { LengthCm=26.2f, WidthCm=25.3f, HeightCm=6.7f, WeightKg=0.144f, FragilePct=0.0f, IrregularPct=81.2f, SampleCount=902 } },
            // [9]11_패션잡화  size_id=2(소형)  n=141
            { 92, new Spec { LengthCm=36.0f, WidthCm=33.5f, HeightCm=12.2f, WeightKg=0.432f, FragilePct=0.0f, IrregularPct=57.4f, SampleCount=141 } },
            // [9]11_패션잡화  size_id=3(중형)  n=155
            { 93, new Spec { LengthCm=48.0f, WidthCm=38.5f, HeightCm=19.0f, WeightKg=1.75f, FragilePct=0.0f, IrregularPct=30.3f, SampleCount=155 } },
            // [9]11_패션잡화  size_id=4(대형)  n=78
            { 94, new Spec { LengthCm=52.0f, WidthCm=45.0f, HeightCm=40.0f, WeightKg=5.21f, FragilePct=0.0f, IrregularPct=15.4f, SampleCount=78 } },
            // [9]11_패션잡화  size_id=5(특대형)  n=12
            { 95, new Spec { LengthCm=71.8f, WidthCm=50.2f, HeightCm=27.5f, WeightKg=3.433f, FragilePct=0.0f, IrregularPct=100.0f, SampleCount=12 } },
            // [9]11_패션잡화  size_id=6(특수)  n=6
            { 96, new Spec { LengthCm=76.4f, WidthCm=36.4f, HeightCm=50.2f, WeightKg=3.506f, FragilePct=0.0f, IrregularPct=100.0f, SampleCount=6 } },
        };

        /// <summary>
        /// classId + size_id 로 스펙 조회. 없으면 해당 classId의 size_id=3(중형) 반환.
        /// </summary>
        public static Spec Get(int classId, int sizeId = 3)
        {
            int key = classId * 10 + sizeId;
            if (_table.TryGetValue(key, out var spec)) return spec;
            // fallback: 중형
            key = classId * 10 + 3;
            if (_table.TryGetValue(key, out spec)) return spec;
            // 최후 fallback: 기본값
            return new Spec { LengthCm=30f, WidthCm=20f, HeightCm=15f, WeightKg=2f };
        }

        /// <summary>classId 에 해당하는 모든 size_id 스펙 목록 반환.</summary>
        public static List<(int sizeId, Spec spec)> GetAll(int classId)
        {
            var result = new List<(int, Spec)>();
            for (int sid = 1; sid <= 6; sid++)
            {
                int key = classId * 10 + sid;
                if (_table.TryGetValue(key, out var s)) result.Add((sid, s));
            }
            return result;
        }

        public static string ClassName(int classId) =>
            classId >= 0 && classId < ClassNames.Length ? ClassNames[classId] : "Unknown";
    }
}